web/router.ex
defmodule Giftrap.Router do
  use Giftrap.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Giftrap.Auth, repo: Giftrap.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug Giftrap.Auth, repo: Giftrap.Repo
  end

  scope "/", Giftrap do
    pipe_through :browser # Use the default browser stack

    resources "/", ImageController, only: [:index]
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    
    resources "/images", ImageController, except: [:index, :show]
  end

  scope "/api/v1", Giftrap do
    pipe_through :api
    
    resources "/tags", TagsController, only: [:index]
    post "/images/:id/click", ImageController, :click
  end
end

web/models/image.ex
defmodule Giftrap.Image do
  use Giftrap.Web, :model

  schema "images" do
    field :url, :string
    field :tags, {:array, :string}
    field :clicks, :integer
    field :tag_list, :string, virtual: true
    belongs_to :user, Giftrap.User

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:url, :tag_list])
    |> validate_required([:url, :tag_list])
    |> filter_tags()
  end
  
  def populate(struct) do
    tag_list = struct.tags |> Enum.join(" ")
    
    %{struct | tag_list: tag_list}
  end
  
  def search(query, term) do
    term
    |> filtered_tags
    |> search_results(query)
  end
    
  def by_user(query, user_id) do
    from i in query,
        where: i.user_id == ^user_id
  end
  
  defp tag_results(result) do
    {columns, rows} = case result do
     {:ok, %{columns: columns, rows: rows}} -> {columns |> Enum.map(&String.to_atom/1) , rows}
      _ -> {[], []}
    end
        
    rows
    |> Enum.map(fn row ->
      Enum.zip(columns, row)
      |> Enum.into(%{})
    end)
  end
  
  def find_tags(search, user_id) do
    Ecto.Adapters.SQL.query(
      Giftrap.Repo, 
      "SELECT * FROM (
        SELECT COUNT(*), UNNEST(tags) AS tag 
          FROM images WHERE user_id = $1 
          GROUP BY tag 
          ORDER BY tag ASC
       ) AS t WHERE t.tag ILIKE $2",
       [user_id, "%#{search}%"]
    )
    |> tag_results
  end
    
  def find_tags(user_id) do
    result = Ecto.Adapters.SQL.query(
      Giftrap.Repo, 
      "SELECT COUNT(*), UNNEST(tags) AS tag FROM images WHERE user_id = $1 GROUP BY tag ORDER BY tag ASC", [user_id]
    )
    
    {columns, rows} = case result do
     {:ok, %{columns: columns, rows: rows}} -> {columns |> Enum.map(&String.to_atom/1) , rows}
      _ -> {[], []}
    end
        
    rows
    |> Enum.map(fn row ->
      Enum.zip(columns, row)
      |> Enum.into(%{})
    end)
  end
  
  defp search_results([], query), do: query
  defp search_results(tag_list, query) do
    from i in query,
      where: fragment("? @> ?", i.tags, ^tag_list)
  end
  
  defp filter_tags(changeset) do
     case changeset do
      %Ecto.Changeset{valid?: true, changes: %{tag_list: tags}} ->
        put_change(changeset, :tags, filtered_tags(tags))
     _ ->
      changeset
    end
  end
  
  defp filtered_tags(tags) when is_binary(tags) do
    tags = String.downcase(tags)
    |> String.replace(~r/[\s,]+/, " ")
    |> String.replace(~r/[^ \p{N}\p{L}_!&<>(){}$^*=:.%+-]+/u, "")
     
    Regex.split(~r/\s+/, tags, trim: true)
    |> Enum.map(&String.trim/1)
    |> Enum.uniq
    |> Enum.reject(&(&1 == ""))
    |> Enum.sort
  end
  defp filtered_tags(_tags), do: []
end

web/controllers/image_controller.ex
defmodule Giftrap.ImageController do
  use Giftrap.Web, :controller

  plug Giftrap.Authenticated

  alias Giftrap.Image
  
  def action(conn, _) do
    apply(__MODULE__, action_name(conn),
      [conn, conn.params, conn.assigns.current_user])
  end
  
  def index(conn, params, user) do
    images = list_images(user.id, params) |> Giftrap.Repo.all
    tags = Image.find_tags(user.id)
    render(conn, "index.html", images: images, tags: tags)
  end
  
  def new(conn, _params, user) do
    changeset = user
    |> build_assoc(:images)
    |> Image.changeset()
    
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"image" => image_params}, user) do
    changeset = user
    |> build_assoc(:images)
    |> Image.changeset(image_params)

    case Repo.insert(changeset) do
      {:ok, _image} ->
        conn
        |> put_flash(:info, "Image created successfully.")
        |> redirect(to: image_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id}, user) do
    image = Repo.get!(user_images(user), id) |> Image.populate
    changeset = Image.changeset(image)
    render(conn, "edit.html", image: image, changeset: changeset)
  end

  def update(conn, %{"id" => id, "image" => image_params}, user) do
    image = Repo.get!(user_images(user), id)
    changeset = Image.changeset(image, image_params)

    case Repo.update(changeset) do
      {:ok, image} ->
        conn
        |> put_flash(:info, "Image updated successfully.")
        |> redirect(to: image_path(conn, :edit, image))
      {:error, changeset} ->
        render(conn, "edit.html", image: Image.populate(image), changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, user) do
    image = Repo.get!(user_images(user), id)
    Repo.delete!(image)

    conn
    |> put_flash(:info, "Image deleted successfully.")
    |> redirect(to: image_path(conn, :index))
  end
  
  def click(conn, %{"id" => id}, user) do
  
   user_images(user)
   |> where([i], i.id == ^id)
   |> Repo.update_all(inc: [clicks: 1])
    
    render(conn, "click.json")
  end
  
  defp user_images(user) do
    assoc(user, :images)
  end
  
  defp list_images(user_id, %{"search" => %{"q" => terms}}) when is_binary(terms) do
    list_images(user_id, %{})
    |> Image.search(terms)
  end
    
  defp list_images(user_id, _) do
    Image
    |> Image.by_user(user_id)
    |> order_by(desc: :inserted_at)

  end
end

web/views/image_view.ex
defmodule Giftrap.ImageView do
  use Giftrap.Web, :view
  
  def render("click.json", _) do
    %{data: :ok}
  end
end

web/templates/image/_grid_image.html.eex
<div class="grid-item grid-item-image">
  <img data-src= "<%= @image.url %>" data-clipboard-text="<%= @image.url %>" data-id="<%= @image.id %>" class="lazy thumb animated" />
  
  <div class="tags">
    <%= for tag <- @image.tags do %>
      <span class="tag"><%= link tag, to: tag_url(@conn, tag) %></span>
    <% end %>
  </div>
  
  <div class="actions">
    <div class="dropdown">
      <span class="option-menu btn btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="glyphicon glyphicon-cog"></span>
      </span>
      
      <%= render Giftrap.ImageView, "_image_menu.html", conn: @conn, image: @image %>
    </div>
  </div>
</div>

web/templates/image/_image_menu.html.eex
<ul class="dropdown-menu dropdown-menu-right dropdown-menu-icon">
  <li><%= link to: image_path(@conn, :edit, @image), title: "Edit", "aria-label": "Edit" do %>
    <span class="glyphicon glyphicon-pencil"></span>
    <% end %>
  </li>
  <li>
    <%= link to: image_path(@conn, :delete, @image), method: :delete, data: [confirm: "Are you sure?"], title: "Delete", "aria-label": "Delete", class: "list-group-item list-group-item-danger" do %>
      <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  </li>
</ul>

web/templates/image/_search_header.html.eex
<div class="row search-nav">
  <div class="search-nav-item col-md-2 col-xs-12 pull-right">
    <%= link "New image", to: image_path(@conn, :new), class: "btn-block btn btn-info pull-right" %>
  </div>
  
  <div class="search-nav-item col-md-6 col-xs-12">
    <%= form_for @conn, image_path(@conn, :index), [as: :search, method: "get", class: "search-form"], fn f -> %>
      <div class="row">
        <div class="form-group col-xs-9">
          <%= text_input f, :q, class: "form-control search tag-field", placeholder: "Search tags..."%>
        </div>
        <div class="form-group col-xs-3">
          <%= submit "Go", class: "btn-block btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

web/templates/image/edit.html.eex
<h2>Edit image</h2>

<%= render "form.html", changeset: @changeset,
                        action: image_path(@conn, :update, @image) %>

<ul class="list-unstyled">
  <li>
    <%= link "Back", to: image_path(@conn, :index) %>
  </li>
</ul>

web/templates/image/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
  
  <%= if @changeset.data.url do %>
    <%= tag :image, src: @changeset.data.url %>
  <% end %>
  
  <div class="form-group">
    <%= label f, :url, class: "control-label" %>
    <%= text_input f, :url, class: "form-control" %>
    <%= error_tag f, :url %>
  </div>

  <div class="form-group">
    <%= label f, :tag_list, class: "control-label" %>
    <%= text_input f, :tag_list, class: "form-control tag-field" %>
    
    <%= error_tag f, :tag_list %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/image/index.html.eex
<%= render Giftrap.ImageView, "_search_header.html", conn: @conn %>

<div class="image-grid">
<%= for image <- @images do %>
  <%= render Giftrap.ImageView, "_grid_image.html", conn: @conn, image: image %>
<% end %>
</div>

web/templates/image/new.html.eex
<h2>New image</h2>

<%= render "form.html", changeset: @changeset,
                        action: image_path(@conn, :create) %>

<%= link "Back", to: image_path(@conn, :index) %>